"""bd swapk

Revision ID: 05be893ffd93
Revises: 
Create Date: 2025-08-21 22:31:11.950446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05be893ffd93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('Administrador', 'Moderador', 'Usuario', 'Verificado', name='rolusuario'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario1_id', sa.Integer(), nullable=True),
    sa.Column('usuario2_id', sa.Integer(), nullable=True),
    sa.Column('Fecha_Creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario1_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario2_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.String(length=255), nullable=True),
    sa.Column('habilidad_Id', sa.Integer(), nullable=True),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.Column('img_Cursos', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['User_Id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['habilidad_Id'], ['habilidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('Nombre', sa.String(length=255), nullable=True),
    sa.Column('Intitucion', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('CV', 'CERTIFICADO', 'ACTA', 'CARTA', 'BECAS', 'CONTRATOS', 'PROYECTOS', name='tipoexpedienteenum'), nullable=True),
    sa.Column('estado', sa.Enum('EN_PROCESO', 'VERIFICADO', 'PENDIENTE', 'RECHAZADO', name='tipoestadoenum'), nullable=True),
    sa.Column('Url_Expediente', sa.String(length=255), nullable=True),
    sa.Column('Fecha_Inicio', sa.DateTime(), nullable=True),
    sa.Column('Fecha_Fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('Recordatorio_Aceptado', 'Recordatorio_Cancelado', 'Curso_Aceptado', 'Curso_Cancelado', 'Recordatorio_Trueque', 'Recordatorio_Curso', 'Mensaje', 'Personalizada', name='tiponotificacion'), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('Tel', sa.Integer(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('habilidad_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_Id'], ['habilidad.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('Enviado', 'Revisado', 'Rechazado', 'Resuelto', 'Cerrado', name='estadoreporte'), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('Nueva_Categoria', 'Mejora_UIUX', 'Mejora_Funcionalidad', 'Sugerencia_General', 'Peticion_Caracteristica', name='tiposugerencia'), nullable=True),
    sa.Column('Mensaje', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('ruta', sa.String(length=255), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('curso_habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Confirmado', 'Finalizado', name='estadoinscripcion'), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_Perfil1', sa.Integer(), nullable=True),
    sa.Column('id_Perfil2', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('Pendiente', 'Confirmado', 'Finalizado', name='estadointercambio'), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_Perfil1'], ['perfiles.id'], ),
    sa.ForeignKeyConstraint(['id_Perfil2'], ['perfiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llamadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('Audio', 'Video', name='tipollamada'), nullable=True),
    sa.Column('Estado', sa.Enum('En_Curso', 'Finalizada', 'Cancelada', name='estadollamada'), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Perfil_Habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('OFRECE', 'BUSCA', name='tipoenum'), nullable=True),
    sa.Column('nivel', sa.Enum('PRINCIPIANTE', 'INTERMEDIO', 'EXPERTO', name='nivelenum'), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('Tamaño_bytes', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('Id_Curso', sa.Integer(), nullable=True),
    sa.Column('Id_Intercambio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_Curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['Id_Intercambio'], ['intercambios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicion_intercambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('condicion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercambio_habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('OFRECE', 'BUSCA', name='tipoenum'), nullable=True),
    sa.Column('nivel', sa.Enum('PRINCIPIANTE', 'INTERMEDIO', 'EXPERTO', name='nivelenum'), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('intercambio_habilidad')
    op.drop_table('condicion_intercambio')
    op.drop_table('archivos')
    op.drop_table('Perfil_Habilidad')
    op.drop_table('mensajes')
    op.drop_table('llamadas')
    op.drop_table('intercambios')
    op.drop_table('inscripciones_cursos')
    op.drop_table('curso_habilidad')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('archivo')
    op.drop_table('sugerencias')
    op.drop_table('reportes')
    op.drop_table('perfiles')
    op.drop_table('notificaciones')
    op.drop_table('expediente')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_table('chat')
    op.drop_table('usuarios')
    op.drop_table('habilidad')
    # ### end Alembic commands ###
