"""bd swapk

Revision ID: 7ab8d6776347
Revises: 
Create Date: 2025-08-21 20:09:13.915731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab8d6776347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llamadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('Audio', 'Video', name='tipollamada'), nullable=True),
    sa.Column('Estado', sa.Enum('En_Curso', 'Finalizada', 'Cancelada', name='estadollamada'), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('Tamaño_bytes', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('Id_Curso', sa.Integer(), nullable=True),
    sa.Column('Id_Intercambio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_Curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['Id_Intercambio'], ['intercambios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicion_intercambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('condicion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercambio_habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('OFRECE', 'BUSCA', name='tipoenum'), nullable=True),
    sa.Column('nivel', sa.Enum('PRINCIPIANTE', 'INTERMEDIO', 'EXPERTO', name='nivelenum'), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intercambio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intercambio_id'], ['intercambios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('intercambio_habilidad')
    op.drop_table('condicion_intercambio')
    op.drop_table('archivos')
    op.drop_table('mensajes')
    op.drop_table('llamadas')
    # ### end Alembic commands ###
